apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flask-monitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: flask-k8s-app  # This should match your Flask service's labels
  endpoints:
  - port: web     # This should match the port name in your Flask service
    interval: 15s
    path: /metrics
  namespaceSelector:
    matchNames:
    - default