apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-k8s-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-k8s-app
  template:
    metadata:
      labels:
        app: flask-k8s-app
    spec:
      containers:
      - name: flask-k8s-app
        image: flask-app:local
        #image: flask-k8s-app:latest  # Use the updated image name
        imagePullPolicy: Never  # Prevent Kubernetes from trying to pull the image
        ports:
          - containerPort: 5000
            name: web # this ensures the port is named consistently between the Deployment and Service
        env:
          - name: DB_HOST
            value: "postgres-service"   

          - name: DB_USER
            value: "postgres"

          - name: DB_PASS
            value: "mystrongpassword"

          - name: DB_NAME
            value: "my_postgres"
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"