apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM= #postgres
  POSTGRES_PASSWORD: bXlzdHJvbmdwYXNzd29yZA== #mystrongpassword
  POSTGRES_DB: bXlfcG9zdGdyZXM= #my_database